# 1. The Numpy Package 

## 1.1 Numpy Array Basics

In [1]:
import numpy as np #import numpy

In [2]:
l = list(range(1,11)) #create a list
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
my_array = np.array(l) #transform list into a numpy array (ndarray)
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
type(my_array) 

numpy.ndarray

In [5]:
for i in my_array: # same as lists, ndarrays store multiple elements (is iterable) 
    print(i)

1
2
3
4
5
6
7
8
9
10


In [6]:
l = [1, 2.5, "Dog", True] #lists can store different datatypes

In [7]:
for i in l:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [8]:
a = np.array(l) #in ndarrays, all elements must have same datatype; numpy transforms automatically
a

array(['1', '2.5', 'Dog', 'True'], dtype='<U32')

In [9]:
for i in a:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [10]:
b = np.array([1., "2", 3])
b

array(['1.0', '2', '3'], dtype='<U32')

In [11]:
type(b)

numpy.ndarray

In [12]:
b.dtype #can check single datatype of all elements with attribute .dtype

dtype('<U32')

## 1.2 Numpy Array (element-wise operations / vectorization)

In [13]:
import numpy as np

In [14]:
np.arange(1,11) #create new ndarray from 1(incl.) to 11(excl.)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(1,11,2) #only every second number is created 

array([1, 3, 5, 7, 9])

In [16]:
l = [1,2,3,4]
l

[1, 2, 3, 4]

In [17]:
l*2 #this is not an element-wise operation

[1, 2, 3, 4, 1, 2, 3, 4]

In [18]:
l1 = [] #element-wise operations with lists require a bunch of code
for i in l:
    l1.append(i*2)
l1

[2, 4, 6, 8]

In [19]:
a = np.arange(1,5) #create ndarray from 1 to 4 (both including)
a

array([1, 2, 3, 4])

In [20]:
a * 2 #element-wise (vectorized) operations are pretty simple with ndarrays

array([2, 4, 6, 8])

In [21]:
a + 2 #addition works as well

array([3, 4, 5, 6])

In [ ]:
a**2 #all elements squared

In [ ]:
2**a #can serve as exponent as well

In [ ]:
np.sqrt(a) #square root of all elements

In [ ]:
np.exp(a) #exponentiation with e

In [ ]:
np.log(a) #natural logarithm

In [ ]:
a.sum() #sum of all elements (ndarray method)

In [ ]:
np.sum(a) #sum of all elements

In [ ]:
sum(a)

In [ ]:
a.size #number of elements in ndarray (ndarray attribute)

In [ ]:
len(a)

In [ ]:
b = np.array([-2, -1, -0.5, 0, 1, 2, 3.5])
b

In [ ]:
np.abs(b) #absolute values of all elements

In [ ]:
c = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
c

In [ ]:
np.ceil(c) #element-wise rounding up

In [ ]:
np.floor(c) #element-wise rounding down

In [ ]:
np.around([-3.23, -0.76, 1.44, 2.65, ], decimals = 0) #evenly round all elements to the given number of decimals.

## 1.3 Numpy Array (Indexing and Slicing)

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1,11) #array from 1 to 10 (incl.)
a

In [ ]:
a[0] #first element at index position 0 (zero-based indexing!)

In [ ]:
a[1] #second element (index position 1)

In [ ]:
a[-1] #last element

In [ ]:
list(enumerate(a)) #list of index,value tuples

In [ ]:
a[2:6] #slicing from index position 2 (incl.) till position 6 (excl.) 

In [ ]:
a[:] #all elements

In [ ]:
a[:5] #all elements until index position 5 (excl.)

In [ ]:
a[6:] #all elements from index position 6 (incl.) till the last element (incl.)

In [ ]:
a[::2] #every second element, starting from first element

In [ ]:
a[::3] #every third element, starting from first element

In [ ]:
a[2::3] #every third element, starting from third element (index position 2)

In [ ]:
a[0] = 100 #ndarrays are mutable, changing first element to 100 
a

In [ ]:
a[-1] = 101 #changing last element to 101
a

In [ ]:
a[2:5] = 50 #in contrast to lists, ndarrays allow braodcasting, assigning one new value to multiple elements
a

In [ ]:
a[2:5] = [50, 51, 52] #assigning multiple new values to multiple elements
a

In [ ]:
a = np.arange(1,11) #creating new ndarray a
a

In [ ]:
b = a[2:8] # making a slice of ndarray a and assign new variable b, 
b
#try b =a[2:8].copy() afterwords

In [ ]:
b[0] = 100 #changing first element of ndarray b
b

In [ ]:
a #respective element of ndarray a has changed as well!!! 

In [ ]:
l = list(range(1,11)) #lists behave differently
l

In [ ]:
m = l[2:8] #here a copy of the slice of l is created
m

In [ ]:
m[0] = 100 #changing first element of slice m
m

In [ ]:
l #no effect on l !!!

## 1.4 Numpy Array (Shape and multiple Dimensions)

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1,13) #creating array from 1 to 12
a

In [ ]:
type(a)

In [ ]:
a.dtype

In [ ]:
a.shape #one-dimensional array, 12 elements in one dimension (vector)

In [ ]:
a = a.reshape(2,6) #reshaping a: 2 rows / 6 columns

In [ ]:
a 

In [ ]:
a.shape # two-dimensional array: 2 rows / 6 columns (matrix)

In [ ]:
a = a.reshape(6,2) # two-dimensional array: 6 rows / 2 columns
a

In [ ]:
a.shape

In [ ]:
a + 100 #element-wise operations still work

In [ ]:
a = a.reshape(2,2,3) #creating a three-dimensional array
a

In [ ]:
a.shape 

In [ ]:
b = np.arange(1,101).reshape(25,4) #creating 2-dim ndarray with one line of code
b

## 1.5 Numpy Array (Indexing and Slicing multi-dimensional arrays)

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1,13)
a

In [ ]:
a = a.reshape(3,4) #creating matrix with 3 rows and 4 columns
a

In [ ]:
a[0] #first row (index position 0)

In [ ]:
a[1] #second row (index position 1)

In [ ]:
a[2] #third row (index position 2)

In [ ]:
a[-1] #last row (index position -1)

In [ ]:
a[1][1] #second row, second column

In [ ]:
a[1,1] #more convenient in one square bracket

In [ ]:
a[2,-1] #third row, last column

In [ ]:
a[:,0] #all rows, first column

In [ ]:
a[:,1] #all rows, second column

In [ ]:
a[:,-1] #all rows, last column

In [ ]:
a[:2,1:3] #first two rows, column two and three

In [ ]:
a

In [ ]:
a.T #Transpose: switching axes (attribute)

In [ ]:
a.transpose() #same (method)

In [ ]:
a

In [ ]:
a[:,-1] = a[:,-1] /4 #changing slice inplace

In [ ]:
a

In [ ]:
a = np.arange(1,13).reshape(3,4) #creating a 3x4 matrix
a

In [ ]:
a.sum() #sum over all elements in matrix

In [ ]:
a.sum(axis = 0) #sum of each column

In [ ]:
a.sum(axis = 1) #sum of each row

In [ ]:
a.cumsum() #cumulative sum of all elements

In [ ]:
a.cumsum(axis = 0) #cumulative sum for each column

In [ ]:
a.cumsum(axis = 1) #cumulative sum for each row

In [ ]:
a

In [ ]:
a.prod() #product over all elements

In [ ]:
a.prod(axis = 0) #product over all elements in each column

In [ ]:
a.prod(axis = 1) #product over all elements in each row